apiVersion: v1
kind: Secret
metadata:
  name: {{ include "aegis-agent.fullname" . }}-secret
  labels:
    {{- include "aegis-agent.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ required "A valid token is required. Pass it via: --set token=XYZ" .Values.token | b64enc }}
